dist: xenial
language: generic
sudo: required
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
install: export CXX="g++-7"
script:
- mkdir build
- cd build
- cmake ../
- make -j8 VERBOSE=1
- cd ../tests
- python3 test_runner.py
